#                           ╭────────────────────────╮
#                           │ 1                      │
#                           │                        │
#                           │   ███╗   ██╗           │
#                           │   ████╗  ██║           │
#                           │   ██╔██╗ ██║   █████╗  │
#                           │   ██║╚██╗██║  ██╔══██╗ │
#                           │   ██║ ╚████║  ███████║ │
#                           │   ╚═╝  ╚═══╝  ██╔════╝ │
#                           │               ╚██████╗ │
#                           │                ╚═════╝ │
#                           │                        │
#                           │       Ne1 Chalk        │
#                           │         v 2.0          │
#                           ╰────────────────────────╯
#
#          ============================================================
#                          Sway Hardware Configuration
#          ============================================================
#                This file dictates display output scaling, monitor
#                resolutions, refresh rates, and specific settings
#                    for trackpads, mice, and input devices.
#          ============================================================

# Touchpad (Generic so tap-to-click works on any laptop)
input type:touchpad {
    tap enabled
    natural_scroll enabled
}
